/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.learn;

import me.learn.datastruct.seqlist.LruCache;
import me.learn.datastruct.seqlist.SingleLinkedList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
//        SingleLinkedList<String> list = new SingleLinkedList<>();
//        list.addAll(new String[]{"1122", "try", "ty", "io"});
//        list.traversal();
//        System.out.println(list.size());

        LruCache<Integer> cache = new LruCache<>();
        cache.access(1);
        cache.access(2);
        cache.access(5);
        cache.access(2);
        cache.access(3);
        cache.access(1);
        cache.access(6);
        cache.access(7);
        cache.access(2);
        cache.traveral();
    }
}
